baseURL = '/'
languageCode = 'es-ar'
title = 'Blog a Pedal'
theme = "LoveIt"
enableInlineShortcodes = true
  [[menu.main]]
  name = "Posts"
  weight = 300
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"
